### ISSUE TITLE
the point of intersection of two hyperbolic line segments

### ISSUE THREAD

**Issue by mckvv** [cduck/hyperbolic#17]
Hello, I would be grateful for any contribution to the discussion on this issue.

I want to determine the intersection of two hyperbolic line-segments, e.g. _AB_ and _CD_ given by these endpoints. But the command _AB.intersectionsWithHcycle.CD_ takes _AB_ and _CD_ as hyperbolic lines. So the result is intersection of the hyperbolic lines _AB_, _CD_ (if it exists) even if the hyperbolic line-segments do not intersect. Is there any way how to fix that? 

Of course, analogous to Euclidean geometry, we could then verify whether the resulting point is the inner point of hyperbolic line-segment _AB_ and _CD_. Let us say, that hyperbolic lines _AB_, _CD_ do intersect in point _X_. Maybe using this command: _R_=hyper.poincare.Point.Point.midpointWith(_A_, _B_, frac = _k_), we can look for such a value of _k_, that _X_ = _R_. But my experiences with Python are very weak. The problem goes further, if e.g. point _D_ is an ideal point, so _CD_ is a hyperbolic ray.

**Comment by cduck** [comment]
Thanks for opening the feature request.  Here is a list of new methods that we need to write for this feature:

- New method `segmentIntersectionsWithHcycle(self, hcycle2)` on [`Hypercycle`](https://github.com/cduck/hyperbolic/blob/master/hyperbolic/poincare/Hypercycle.py#L101).  This method will first call [`intersectionsWithHcycle`](https://github.com/cduck/hyperbolic/blob/master/hyperbolic/poincare/Hypercycle.py#L54) and only return the points that are true for `self.isPointOnSegment(x, y)` and `hcycle2.isPointOnSegment(x, y)`.  This methods does what you want by only returning the intersections that are contained within both segments and returning nothing otherwise.

Helper methods:
- New method `isPointOnSegment(self, x, y)` on [`Hypercycle`](https://github.com/cduck/hyperbolic/blob/master/hyperbolic/poincare/Hypercycle.py#L101).  Check if the point is between or outside the endpoints by asking its underlying euclidean shape: `return self.projShape.isPointOnSegment(x, y)` (see below)

- New method `isPointOnSegment(self, x, y)` on [`euclid.Line`](https://github.com/cduck/hyperbolic/blob/master/hyperbolic/euclid/Line.py#L43).  This method will check if the point is between or outside the endpoints.
- New method `isPointOnSegment(self, x, y)` on [`euclid.Circle`](https://github.com/cduck/hyperbolic/blob/master/hyperbolic/euclid/Line.py#L43).  Always returns true because a circle doesn't have endpoints.
- New method `isPointOnSegment(self, x, y)` on [`euclid.Circle`](https://github.com/cduck/hyperbolic/blob/master/hyperbolic/euclid/Arc.py#L42).  Checks if the point's radial angle is between startDeg and endDeg.

Let me know if you need more detail or have any questions.

**Comment by mckvv** [comment]
This looks gret! Thank you for now.
I understand better what we need to do. But I am afraid, that with my experience I'm not able to implement these features by myself. Could you help me with that? I think similar features would be useful for other users.

**Comment by smh0109** [comment]
Apparently I was working on a very similar feature rigth now, I could probably create a branch to impelment this...

**Comment by cduck** [comment]
That would be great @smh0109.  Post here or open a pull request if you want any feedback.
