### ISSUE TITLE
Help creating Farey diagram

### ISSUE THREAD

**Issue by diramazioni** [cduck/hyperbolic#4]
Hello, and congratulation for this and drawSvg.
I'm trying to replicate the [Farey diagram](https://i.stack.imgur.com/GO2md.png)[ like asked here](https://mathematica.stackexchange.com/questions/194838/how-can-i-plot-a-farey-diagram) for mathematica.
Is it possible?

**Comment by cduck** [comment]
Thanks.  That diagram is a regular tiling of triangles where each vertex is surrounded by an infinite number of triangles.  Try out [examples/tiles.ipynb](https://github.com/cduck/hyperbolic/blob/master/examples/tiles.ipynb) and [examples/poincare.ipynb (cell 10)](https://github.com/cduck/hyperbolic/blob/master/examples/poincare.ipynb) and set the value of `q` to a large number.  (You'll have to translate the origin to place an edge in the center instead of a triangle.)

**Comment by cduck** [comment]
Closing as this tiling is already supported.
